spring:
  rabbitmq:
    addresses: 192.168.0.153:5672
    username: admin
    password: admin
    virtual-host: my_vhost
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.sxw.springbootproducer
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    tk:
      mybatis: trace
