## springboot整合rabbitmq的基本配置
spring:
  rabbitmq:
    addresses: 192.168.0.153:5672
    username: admin
    password: admin
    virtual-host: my_vhost
## 消费端配置
    listener:
      simple:
        concurrency: 1
        ## manual:手动 ack（确认）
        acknowledge-mode: manual
        max-concurrency: 1
        prefetch: 10
  datasource:
      url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
server:
  port: 8002
  servlet:
    context-path: /